class NewUserError(Exception):
    pass

class LoginError(Exception):
    pass
